"""Generate bundle instance pool + recon job cluster config from cluster_config.json."""

from __future__ import annotations

from pathlib import Path

from util.bundle_config import (
    HEARTBEAT_JOB_ALERT_MAIL_VAR_REF,
    JOB_TAG_VAR_REF,
    PIPELINE_CLUSTER_NUM_WORKERS_VAR_REF,
    PIPELINE_SPARK_VERSION_VAR_REF,
    RECON_POLL_INTERVAL_SEC_VAR_REF,
    RECON_POOL_MAX_CAPACITY_VAR_REF,
    RECON_POOL_MIN_IDLE_INSTANCES_VAR_REF,
)
from util.models import ClusterConfig, ClusterTierName, ReconPoolConfig

RECON_JOB_CLUSTER_KEY = "recon_cluster"
DEFAULT_RECON_POOL = ReconPoolConfig()


def _resolve_recon_tier(cluster_config: ClusterConfig, recon_tier_key: ClusterTierName):
    tier = cluster_config.tiers.get(recon_tier_key)
    if tier is None:
        raise ValueError(f"recon tier '{recon_tier_key}' not in cluster_config.json")
    if tier.serverless:
        raise ValueError(f"recon tier must be a job tier (j1, j2, j3); got {recon_tier_key}")
    return tier


def _effective_recon_pool(
    cluster_config: ClusterConfig,
    recon_tier_key: ClusterTierName,
) -> ReconPoolConfig:
    pool = cluster_config.recon_pool or DEFAULT_RECON_POOL
    tier_key = pool.tier or recon_tier_key
    tier = _resolve_recon_tier(cluster_config, tier_key)
    if not tier.node_type_id:
        raise ValueError(f"recon pool tier '{tier_key}' needs node_type_id in cluster_config.json")
    return pool


def _pool_resource_ref(pool: ReconPoolConfig) -> str:
    return f"${{resources.instance_pools.{pool.bundle_resource_key}.id}}"


def generate_recon_instance_pool_yaml(
    cluster_config: ClusterConfig,
    recon_tier_key: ClusterTierName,
) -> str:
    pool = _effective_recon_pool(cluster_config, recon_tier_key)
    tier = _resolve_recon_tier(cluster_config, pool.tier)

    lines = [
        "# Generated by ipac-delta-sync from cluster_config.json recon_pool + tier "
        f"{pool.tier}.",
        "# D32 instance pool (separate quota from pipeline clusters).",
        "# Regenerate: ipac-delta-sync generate",
        "resources:",
        "  instance_pools:",
        f"    {pool.bundle_resource_key}:",
        f"      instance_pool_name: {pool.instance_pool_name}",
        f"      min_idle_instances: {RECON_POOL_MIN_IDLE_INSTANCES_VAR_REF}",
        f"      max_capacity: {RECON_POOL_MAX_CAPACITY_VAR_REF}",
        f"      node_type_id: {tier.node_type_id}",
        "      idle_instance_autotermination_minutes: 30",
        "      preloaded_spark_versions:",
        f"        - {PIPELINE_SPARK_VERSION_VAR_REF}",
        "      custom_tags:",
        f"        bundle: {JOB_TAG_VAR_REF}",
        "        purpose: sql_recon_pool",
    ]
    return "\n".join(lines) + "\n"


def generate_ingestion_recon_job_yaml(
    cluster_config: ClusterConfig,
    recon_tier_key: ClusterTierName,
) -> str:
    pool = _effective_recon_pool(cluster_config, recon_tier_key)
    tier = _resolve_recon_tier(cluster_config, pool.tier)
    pool_ref = _pool_resource_ref(pool)

    lines = [
        "# Generated by ipac-delta-sync — recon job on instance pool "
        f"{pool.instance_pool_name} (tier {pool.tier}).",
        "# Not serverless — on-prem SQL Server via VNet/integration.",
        "# Regenerate: ipac-delta-sync generate",
        "resources:",
        "  jobs:",
        "    ingestion_recon_monitor:",
        "      name: j_ipac_delta_sync_ingestion_recon_monitor",
        "      max_concurrent_runs: 1",
        "      timeout_seconds: 0",
        "      permissions:",
        "        - level: CAN_MANAGE",
        "          group_name: ${var.grant_group}",
        "      tags:",
        f"        bundle: {JOB_TAG_VAR_REF}",
        "      email_notifications:",
        "        on_failure:",
        f"          - {HEARTBEAT_JOB_ALERT_MAIL_VAR_REF}",
        "      continuous:",
        "        pause_status: UNPAUSED",
        "      job_clusters:",
        f"        - job_cluster_key: {RECON_JOB_CLUSTER_KEY}",
        "          new_cluster:",
        f"            instance_pool_id: {pool_ref}",
        f"            spark_version: {PIPELINE_SPARK_VERSION_VAR_REF}",
        f"            num_workers: {PIPELINE_CLUSTER_NUM_WORKERS_VAR_REF}",
        "            spark_conf:",
        "              spark.databricks.cluster.profile: singleNode",
        f"              spark.master: local[{tier.local_cores}]",
        "            custom_tags:",
        "              ResourceClass: SingleNode",
        f"              bundle: {JOB_TAG_VAR_REF}",
        "              purpose: sql_recon",
        "      tasks:",
        "        - task_key: run_ingestion_recon",
        f"          job_cluster_key: {RECON_JOB_CLUSTER_KEY}",
        "          notebook_task:",
        "            notebook_path: ${workspace.file_path}/src/common/notebooks/run_ingestion_recon.py",
        "            base_parameters:",
        "              uc_catalog: ${resources.schemas.schema_ipac_metadata.catalog_name}",
        "              ipac_metadata_schema: ${resources.schemas.schema_ipac_metadata.name}",
        "              pipeline_names_file: ${workspace.file_path}/generated/config/pipeline_names.json",
        "              dest_schema_suffix: ${var.dest_schema_suffix}",
        f"              poll_interval_sec: {RECON_POLL_INTERVAL_SEC_VAR_REF}",
    ]
    return "\n".join(lines) + "\n"


def write_recon_instance_pool_yaml(
    cluster_config: ClusterConfig,
    recon_tier_key: ClusterTierName,
    output_path: Path,
) -> str:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        generate_recon_instance_pool_yaml(cluster_config, recon_tier_key),
        encoding="utf-8",
    )
    return str(output_path)


def write_ingestion_recon_job_yaml(
    cluster_config: ClusterConfig,
    recon_tier_key: ClusterTierName,
    output_path: Path,
) -> str:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        generate_ingestion_recon_job_yaml(cluster_config, recon_tier_key),
        encoding="utf-8",
    )
    return str(output_path)
