"""Generate recon job YAML with single-node cluster from cluster_config.json tier."""

from __future__ import annotations

from pathlib import Path

from util.bundle_config import (
    HEARTBEAT_JOB_ALERT_MAIL_VAR_REF,
    IPAC_METADATA_SCHEMA_VAR_REF,
    JOB_TAG_VAR_REF,
    LAKEFLOW_SINGLE_USER_VAR_REF,
    PIPELINE_CLUSTER_NUM_WORKERS_VAR_REF,
    PIPELINE_SPARK_VERSION_VAR_REF,
    RECON_POLL_INTERVAL_SEC_VAR_REF,
    UC_CATALOG_VAR_REF,
)
from util.cluster_tiers import format_job_cluster_spec_lines
from util.models import ClusterConfig, ClusterTierName

RECON_JOB_CLUSTER_KEY = "recon_j2"


def _resolve_recon_tier(cluster_config: ClusterConfig, recon_tier_key: ClusterTierName):
    tier = cluster_config.tiers.get(recon_tier_key)
    if tier is None:
        raise ValueError(f"recon_cluster_tier '{recon_tier_key}' not in cluster_config.json")
    if tier.serverless:
        raise ValueError(f"recon_cluster_tier must be j1, j2, or j3; got {recon_tier_key}")
    return tier


def generate_ingestion_recon_job_yaml(
    cluster_config: ClusterConfig,
    recon_tier_key: ClusterTierName,
) -> str:
    tier = _resolve_recon_tier(cluster_config, recon_tier_key)
    cluster_lines = format_job_cluster_spec_lines(
        tier,
        spark_version_ref=PIPELINE_SPARK_VERSION_VAR_REF,
        num_workers_ref=PIPELINE_CLUSTER_NUM_WORKERS_VAR_REF,
        single_user_name_ref=LAKEFLOW_SINGLE_USER_VAR_REF,
        indent="            ",
        include_single_node_custom_tag=False,
    )

    lines = [
        "# Generated by ipac-delta-sync from cluster_config.json tier "
        f"{recon_tier_key} (recon_cluster_tier).",
        "# Fixed single-node j2 D32 job cluster — NOT serverless (on-prem SQL Server).",
        "# Regenerate: ipac-delta-sync generate",
        "resources:",
        "  jobs:",
        "    ingestion_recon_monitor:",
        "      name: j_ipac_delta_sync_ingestion_recon_monitor",
        "      max_concurrent_runs: 1",
        "      timeout_seconds: 0",
        "      permissions:",
        "        - level: CAN_MANAGE",
        "          group_name: ${var.grant_group}",
        "      tags:",
        f"        bundle: {JOB_TAG_VAR_REF}",
        "      email_notifications:",
        "        on_failure:",
        f"          - {HEARTBEAT_JOB_ALERT_MAIL_VAR_REF}",
        "      continuous:",
        "        pause_status: UNPAUSED",
        "      job_clusters:",
        f"        - job_cluster_key: {RECON_JOB_CLUSTER_KEY}",
        "          new_cluster:",
        *cluster_lines,
        "            custom_tags:",
        "              ResourceClass: SingleNode",
        f"              bundle: {JOB_TAG_VAR_REF}",
        "              purpose: sql_recon",
        "      tasks:",
        "        - task_key: run_ingestion_recon",
        f"          job_cluster_key: {RECON_JOB_CLUSTER_KEY}",
        "          notebook_task:",
        "            notebook_path: ${workspace.file_path}/src/common/notebooks/run_ingestion_recon.py",
        "            base_parameters:",
        f"              uc_catalog: {UC_CATALOG_VAR_REF}",
        f"              ipac_metadata_schema: {IPAC_METADATA_SCHEMA_VAR_REF}",
        "              pipeline_names_file: ${workspace.file_path}/generated/config/pipeline_names.json",
        "              dest_schema_suffix: ${var.dest_schema_suffix}",
        f"              poll_interval_sec: {RECON_POLL_INTERVAL_SEC_VAR_REF}",
    ]
    return "\n".join(lines) + "\n"


def write_ingestion_recon_job_yaml(
    cluster_config: ClusterConfig,
    recon_tier_key: ClusterTierName,
    output_path: Path,
) -> str:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        generate_ingestion_recon_job_yaml(cluster_config, recon_tier_key),
        encoding="utf-8",
    )
    return str(output_path)
