"""Generate bundle cluster resources from cluster_config.json tiers."""

from __future__ import annotations

from pathlib import Path

from util.bundle_config import (
    JOB_TAG_VAR_REF,
    PIPELINE_CLUSTER_NUM_WORKERS_VAR_REF,
    PIPELINE_SPARK_VERSION_VAR_REF,
    SQL_RECON_AUTOTERMINATION_MINUTES_VAR_REF,
)
from util.cluster_tiers import format_job_cluster_spec_lines
from util.models import ClusterConfig, ClusterTierName


def generate_recon_cluster_yaml(
    cluster_config: ClusterConfig,
    recon_tier_key: ClusterTierName,
) -> str:
    tier = cluster_config.tiers.get(recon_tier_key)
    if tier is None:
        raise ValueError(f"recon_cluster_tier '{recon_tier_key}' not in cluster_config.json")
    if tier.serverless:
        raise ValueError(f"recon_cluster_tier must be a job tier (j1, j2, j3); got {recon_tier_key}")

    spec_lines = format_job_cluster_spec_lines(
        tier,
        spark_version_ref=PIPELINE_SPARK_VERSION_VAR_REF,
        num_workers_ref=PIPELINE_CLUSTER_NUM_WORKERS_VAR_REF,
        indent="      ",
    )

    lines = [
        "# Generated by ipac-delta-sync from cluster_config.json tier "
        f"{recon_tier_key} (recon_cluster_tier)",
        "resources:",
        "  clusters:",
        "    ipac_sql_recon_cluster:",
        "      cluster_name: ipac_sql_recon_shared",
        *spec_lines,
        "      custom_tags:",
        f"        bundle: {JOB_TAG_VAR_REF}",
        "        purpose: sql_recon",
        "        ResourceClass: SingleNode",
        "      runtime_engine: STANDARD",
        f"      autotermination_minutes: {SQL_RECON_AUTOTERMINATION_MINUTES_VAR_REF}",
        "      enable_elastic_disk: true",
        "      permissions:",
        "        - level: CAN_MANAGE",
        "          group_name: ${var.grant_group}",
        "        - level: CAN_RESTART",
        "          group_name: ${var.grant_group}",
        "        - level: CAN_ATTACH_TO",
        "          group_name: ${var.grant_group}",
    ]
    return "\n".join(lines) + "\n"


def write_recon_cluster_resource_yaml(
    cluster_config: ClusterConfig,
    recon_tier_key: ClusterTierName,
    output_dir: Path,
) -> str:
    out = output_dir / "ipac_sql_recon_cluster.yml"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        generate_recon_cluster_yaml(cluster_config, recon_tier_key),
        encoding="utf-8",
    )
    return str(out)
