"""Generate a bundle job that starts all generated continuous Lakeflow pipelines."""

from __future__ import annotations

from util.bundle_config import JOB_TAG_VAR_REF

GRANT_GROUP_VAR_REF = "${var.grant_group}"
HEARTBEAT_JOB_ALERT_MAIL_VAR_REF = "${var.heartbeat_job_alert_mail}"


def pipeline_start_task_key(pipeline_key: str) -> str:
    """Build a Databricks task_key from a pipeline resource key."""
    safe = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in pipeline_key)
    return f"start_{safe}"


def generate_continuous_ingest_job_yaml(
    pipeline_keys: list[str],
    *,
    grant_group_ref: str = GRANT_GROUP_VAR_REF,
    job_tag_ref: str = JOB_TAG_VAR_REF,
    alert_email_ref: str = HEARTBEAT_JOB_ALERT_MAIL_VAR_REF,
) -> str:
    """Emit bundle YAML for one job with a pipeline_task per generated pipeline.

    Run once after deploy: ``databricks bundle run continuous_ingest_all -t dev``.
    The job run stays RUNNING while continuous pipelines are up.
    """
    unique_keys = sorted({key.strip() for key in pipeline_keys if key and key.strip()})
    if not unique_keys:
        raise ValueError("No pipeline keys to include in continuous ingest job")

    lines = [
        "# Generated by ipac_delta_sync — starts all generated continuous pipelines.",
        "# Regenerate: ipac-delta-sync generate",
        "# Run:       databricks bundle run continuous_ingest_all -t dev",
        f"# pipelines: {len(unique_keys)}",
        "resources:",
        "  jobs:",
        "    continuous_ingest_all:",
        "      name: j_ipac_delta_sync_continuous_ingest",
        "      max_concurrent_runs: 1",
        "      permissions:",
        "        - level: CAN_MANAGE",
        f"          group_name: {grant_group_ref}",
        "      tags:",
        f"        bundle: {job_tag_ref}",
        "      email_notifications:",
        "        on_failure:",
        f"          - {alert_email_ref}",
        "      depends_on:",
    ]

    for pipeline_key in unique_keys:
        lines.append(f"        - resources.pipelines.{pipeline_key}")

    lines.append("      tasks:")

    for pipeline_key in unique_keys:
        task_key = pipeline_start_task_key(pipeline_key)
        lines.extend(
            [
                f"        - task_key: {task_key}",
                "          pipeline_task:",
                f"            pipeline_id: ${{resources.pipelines.{pipeline_key}.id}}",
            ]
        )

    return "\n".join(lines) + "\n"


def write_continuous_ingest_job_yaml(
    pipeline_keys: list[str],
    output_dir,
    *,
    grant_group_ref: str = GRANT_GROUP_VAR_REF,
    job_tag_ref: str = JOB_TAG_VAR_REF,
    alert_email_ref: str = HEARTBEAT_JOB_ALERT_MAIL_VAR_REF,
) -> str:
    from pathlib import Path

    out_file = Path(output_dir) / "continuous_ingest_job.yml"
    content = generate_continuous_ingest_job_yaml(
        pipeline_keys,
        grant_group_ref=grant_group_ref,
        job_tag_ref=job_tag_ref,
        alert_email_ref=alert_email_ref,
    )
    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text(content, encoding="utf-8")
    return str(out_file)
