"""Unity Catalog schema resource helpers for bundle deployment."""

from __future__ import annotations

from pathlib import Path

from util.bundle_config import IPAC_METADATA_SCHEMA_VAR_REF, UC_CATALOG_VAR_REF
from util.models import ClientEntry

IPAC_METADATA_SCHEMA_RESOURCE_KEY = "schema_ipac_metadata"


def schema_resource_key(schema_name: str) -> str:
    key = schema_name.lower().replace("-", "_")
    return f"schema_{key}"


def schema_resource_catalog_ref(schema_name: str) -> str:
    key = schema_resource_key(schema_name)
    return f"${{resources.schemas.{key}.catalog_name}}"


def schema_resource_name_ref(schema_name: str) -> str:
    key = schema_resource_key(schema_name)
    return f"${{resources.schemas.{key}.name}}"


def format_schema_resource_lines(
    schema_name: str,
    uc_catalog_ref: str,
    comment: str,
) -> list[str]:
    key = schema_resource_key(schema_name)
    return [
        f"    {key}:",
        f"      name: {schema_name}",
        f"      catalog_name: {uc_catalog_ref}",
        f"      comment: \"{comment}\"",
    ]


def generate_schema_resource_yaml(
    schema_name: str,
    uc_catalog_ref: str,
    comment: str,
) -> str:
    lines = [
        "resources:",
        "  schemas:",
    ]
    lines.extend(format_schema_resource_lines(schema_name, uc_catalog_ref, comment))
    return "\n".join(lines) + "\n"


def write_client_schema_resource_yaml(
    client: ClientEntry,
    dest_schema_suffix: str,
    output_dir: Path | str,
    uc_catalog_ref: str,
) -> str:
    """Write per-client raw schema bundle resource under generated/config/schema/."""
    schema_name = client.raw_schema(dest_schema_suffix)
    header = (
        f"# Generated by ipac_delta_sync for client: {client.client_nm}\n"
        f"# Deployed before pipelines via depends_on on p_{client.client_nm}_*\n"
    )
    content = header + generate_schema_resource_yaml(
        schema_name,
        uc_catalog_ref,
        f"iPAC delta sync schema for client {client.client_nm} (raw + staging)",
    )
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{client.client_nm}_schema.yml"
    out_file.write_text(content, encoding="utf-8")
    return str(out_file)


def write_ipac_metadata_schema_resource_yaml(
    output_dir: Path | str,
    uc_catalog_ref: str = UC_CATALOG_VAR_REF,
    metadata_schema_name_ref: str = IPAC_METADATA_SCHEMA_VAR_REF,
) -> str:
    """Write shared ipac_metadata UC schema bundle resource (catalog + name from bundle vars)."""
    header = (
        "# Generated by ipac_delta_sync — shared metadata schema for all clients\n"
        "# Recreated on bundle deploy if missing (process_log, recon, watermarks)\n"
        "# Deployed before pipelines via depends_on on p_* resources\n"
    )
    lines = [
        "resources:",
        "  schemas:",
        f"    {IPAC_METADATA_SCHEMA_RESOURCE_KEY}:",
        f"      name: {metadata_schema_name_ref}",
        f"      catalog_name: {uc_catalog_ref}",
        "      comment: \"iPAC metadata schema for process logs, recon tables, and event log watermarks\"",
    ]
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / "ipac_metadata_schema.yml"
    out_file.write_text(header + "\n".join(lines) + "\n", encoding="utf-8")
    return str(out_file)
