"""Generate SQL artifacts for source SQL Server preparation."""

from __future__ import annotations

from pathlib import Path

from util.models import ClientEntry, EffectiveTable


def _sql_ident(name: str) -> str:
    return name.replace("]", "]]")


def _sql_literal(value: str) -> str:
    return value.replace("'", "''")


def _table_list_values_sql(tables: list[EffectiveTable]) -> list[str]:
    names = sorted({t.table_nm for t in tables}, key=str.lower)
    return [f"(N'{_sql_literal(name)}')" for name in names]


def _client_sql_header(client: ClientEntry, purpose: str) -> list[str]:
    return [
        f"-- Auto-generated by ipac_delta_sync for client: {client.client_nm}",
        f"-- Source DB: {client.src_db_nm}, schema: {client.src_db_schema}",
        f"-- Purpose: {purpose}",
        "",
        f"USE [{_sql_ident(client.src_db_nm)}];",
        "GO",
        "",
    ]


def _table_list_setup(schema_literal: str, values: list[str]) -> list[str]:
    return [
        "IF OBJECT_ID('tempdb..#table_list') IS NOT NULL DROP TABLE #table_list;",
        "CREATE TABLE #table_list (table_name SYSNAME NOT NULL PRIMARY KEY);",
        "",
        "INSERT INTO #table_list (table_name) VALUES",
        "    " + ",\n    ".join(values) + ";",
        "",
    ]


def generate_enable_ct_or_cdc_sql(
    client: ClientEntry,
    tables: list[EffectiveTable],
) -> str:
    """Enable CT when table has PK (and CT off); enable CDC when no PK (idempotent)."""
    values = _table_list_values_sql(tables)
    db_ident = _sql_ident(client.src_db_nm)
    lines = _client_sql_header(
        client,
        "enable CT (PK tables) or CDC (non-PK tables) — run grant scripts after this",
    )
    lines.extend(
        [
            "-- Database-level Change Tracking (ALTER DATABASE must run in its own batch)",
            "IF NOT EXISTS (SELECT 1 FROM sys.change_tracking_databases WHERE database_id = DB_ID())",
            "BEGIN",
            (
                f"    EXEC(N'ALTER DATABASE [{db_ident}] SET CHANGE_TRACKING = ON\n"
                "(CHANGE_RETENTION = 2, AUTO_CLEANUP = ON);');"
            ),
            "    PRINT 'Database Change Tracking enabled.';",
            "END",
            "GO",
            "",
            "-- Database-level CDC",
            "IF (SELECT is_cdc_enabled FROM sys.databases WHERE database_id = DB_ID()) = 0",
            "BEGIN",
            "    EXEC sys.sp_cdc_enable_db;",
            "    PRINT 'Database CDC enabled.';",
            "END",
            "GO",
            "",
            "SET NOCOUNT ON;",
            "",
            "DECLARE @schema SYSNAME = N'" + _sql_literal(client.src_db_schema) + "';",
            "DECLARE @table SYSNAME;",
            "DECLARE @sql NVARCHAR(MAX);",
            "DECLARE @object_id INT;",
            "DECLARE @has_pk BIT;",
            "",
        ]
    )
    lines.extend(_table_list_setup(_sql_literal(client.src_db_schema), values))
    lines.extend(
        [
            "DECLARE table_cursor CURSOR LOCAL FAST_FORWARD FOR",
            "    SELECT table_name FROM #table_list ORDER BY table_name;",
            "",
            "OPEN table_cursor;",
            "FETCH NEXT FROM table_cursor INTO @table;",
            "",
            "WHILE @@FETCH_STATUS = 0",
            "BEGIN",
            "    SET @object_id = OBJECT_ID(QUOTENAME(@schema) + '.' + QUOTENAME(@table));",
            "",
            "    IF @object_id IS NULL",
            "    BEGIN",
            "        PRINT N'SKIP (missing): ' + @schema + N'.' + @table;",
            "    END",
            "    ELSE",
            "    BEGIN",
            "        SET @has_pk = CASE",
            "            WHEN EXISTS (",
            "                SELECT 1 FROM sys.indexes",
            "                WHERE object_id = @object_id AND is_primary_key = 1",
            "            ) THEN 1 ELSE 0",
            "        END;",
            "",
            "        IF @has_pk = 1",
            "        BEGIN",
            "            IF NOT EXISTS (",
            "                SELECT 1 FROM sys.change_tracking_tables WHERE object_id = @object_id",
            "            )",
            "            BEGIN",
            "                SET @sql = N'ALTER TABLE ' + QUOTENAME(@schema) + N'.' + QUOTENAME(@table)",
            "                    + N' ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);';",
            "                EXEC sp_executesql @sql;",
            "                PRINT N'CT enabled: ' + @schema + N'.' + @table;",
            "            END",
            "            ELSE",
            "                PRINT N'CT already enabled: ' + @schema + N'.' + @table;",
            "        END",
            "        ELSE",
            "        BEGIN",
            "            IF NOT EXISTS (",
            "                SELECT 1 FROM cdc.change_tables WHERE source_object_id = @object_id",
            "            )",
            "            BEGIN",
            "                EXEC sys.sp_cdc_enable_table",
            "                    @source_schema = @schema,",
            "                    @source_name   = @table,",
            "                    @role_name     = NULL,",
            "                    @supports_net_changes = 0;",
            "                PRINT N'CDC enabled: ' + @schema + N'.' + @table;",
            "            END",
            "            ELSE",
            "                PRINT N'CDC already enabled: ' + @schema + N'.' + @table;",
            "        END",
            "    END",
            "",
            "    FETCH NEXT FROM table_cursor INTO @table;",
            "END",
            "",
            "CLOSE table_cursor;",
            "DEALLOCATE table_cursor;",
            "",
            "PRINT 'Done. Run grant_ct_access.sql and grant_cdc_access.sql next.';",
            "GO",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def _ensure_database_user_lines() -> list[str]:
    """Map a server login to a database user before GRANT (required for server-level principals)."""
    principal_expr = "REPLACE(@principal, ']', ']]')"
    return [
        "-- Server logins must exist as database users before GRANT",
        "IF NOT EXISTS (SELECT 1 FROM sys.database_principals WHERE name = @principal)",
        "BEGIN",
        "    IF EXISTS (SELECT 1 FROM sys.server_principals WHERE name = @principal)",
        "    BEGIN",
        "        SET @sql = N'CREATE USER [' + " + principal_expr + " + N'] FOR LOGIN [' + " + principal_expr + " + N'];';",
        "        EXEC sp_executesql @sql;",
        "        PRINT N'Created database user for server login: ' + @principal;",
        "    END",
        "    ELSE",
        "    BEGIN",
        "        RAISERROR(N'Principal not found as database user or server login: %s', 16, 1, @principal);",
        "        RETURN;",
        "    END",
        "END",
        "",
    ]


def _generate_dynamic_ct_grants_body(schema_literal: str, values: list[str]) -> list[str]:
    principal_expr = "REPLACE(@principal, ']', ']]')"
    lines = [
        "SET NOCOUNT ON;",
        "",
        "DECLARE @schema SYSNAME = N'" + schema_literal + "';",
        "DECLARE @table SYSNAME;",
        "DECLARE @sql NVARCHAR(MAX);",
        "DECLARE @object_id INT;",
        "DECLARE @has_pk BIT;",
        "",
    ]
    lines.extend(_ensure_database_user_lines())
    lines.extend(_table_list_setup(schema_literal, values))
    lines.extend(
        [
            "SET @sql = N'GRANT VIEW DATABASE STATE TO [' + " + principal_expr + " + N']';",
            "EXEC sp_executesql @sql;",
            "",
            "SET @sql = N'GRANT VIEW CHANGE TRACKING ON SCHEMA::' + QUOTENAME(@schema)",
            "    + N' TO [' + " + principal_expr + " + N']';",
            "EXEC sp_executesql @sql;",
            "",
            "DECLARE grant_cursor CURSOR LOCAL FAST_FORWARD FOR",
            "    SELECT table_name FROM #table_list ORDER BY table_name;",
            "",
            "OPEN grant_cursor;",
            "FETCH NEXT FROM grant_cursor INTO @table;",
            "",
            "WHILE @@FETCH_STATUS = 0",
            "BEGIN",
            "    SET @object_id = OBJECT_ID(QUOTENAME(@schema) + '.' + QUOTENAME(@table));",
            "",
            "    IF @object_id IS NULL",
            "        PRINT N'SKIP (missing): ' + @schema + N'.' + @table;",
            "    ELSE",
            "    BEGIN",
            "        SET @has_pk = CASE",
            "            WHEN EXISTS (",
            "                SELECT 1 FROM sys.indexes",
            "                WHERE object_id = @object_id AND is_primary_key = 1",
            "            ) THEN 1 ELSE 0",
            "        END;",
            "",
            "        IF @has_pk = 0",
            "            PRINT N'SKIP (no PK / use CDC grants): ' + @schema + N'.' + @table;",
            "        ELSE IF NOT EXISTS (",
            "            SELECT 1 FROM sys.change_tracking_tables WHERE object_id = @object_id",
            "        )",
            "            PRINT N'SKIP (CT not enabled): ' + @schema + N'.' + @table;",
            "        ELSE",
            "        BEGIN",
            "            SET @sql = N'GRANT SELECT, VIEW CHANGE TRACKING ON '",
            "                + QUOTENAME(@schema) + N'.' + QUOTENAME(@table)",
            "                + N' TO [' + " + principal_expr + " + N']';",
            "            EXEC sp_executesql @sql;",
            "            PRINT N'CT grants applied: ' + @schema + N'.' + @table;",
            "        END",
            "    END",
            "",
            "    FETCH NEXT FROM grant_cursor INTO @table;",
            "END",
            "",
            "CLOSE grant_cursor;",
            "DEALLOCATE grant_cursor;",
            "GO",
            "",
        ]
    )
    return lines


def _generate_dynamic_cdc_grants_body(schema_literal: str, values: list[str]) -> list[str]:
    principal_expr = "REPLACE(@principal, ']', ']]')"
    lines = [
        "SET NOCOUNT ON;",
        "",
        "DECLARE @schema SYSNAME = N'" + schema_literal + "';",
        "DECLARE @table SYSNAME;",
        "DECLARE @sql NVARCHAR(MAX);",
        "DECLARE @object_id INT;",
        "DECLARE @has_pk BIT;",
        "DECLARE @capture_instance SYSNAME;",
        "DECLARE @cdc_change_table SYSNAME;",
        "",
    ]
    lines.extend(_ensure_database_user_lines())
    lines.extend(_table_list_setup(schema_literal, values))
    lines.extend(
        [
            "SET @sql = N'GRANT VIEW DATABASE STATE TO [' + " + principal_expr + " + N']';",
            "EXEC sp_executesql @sql;",
            "",
            "DECLARE grant_cursor CURSOR LOCAL FAST_FORWARD FOR",
            "    SELECT table_name FROM #table_list ORDER BY table_name;",
            "",
            "OPEN grant_cursor;",
            "FETCH NEXT FROM grant_cursor INTO @table;",
            "",
            "WHILE @@FETCH_STATUS = 0",
            "BEGIN",
            "    SET @object_id = OBJECT_ID(QUOTENAME(@schema) + '.' + QUOTENAME(@table));",
            "",
            "    IF @object_id IS NULL",
            "        PRINT N'SKIP (missing): ' + @schema + N'.' + @table;",
            "    ELSE",
            "    BEGIN",
            "        SET @has_pk = CASE",
            "            WHEN EXISTS (",
            "                SELECT 1 FROM sys.indexes",
            "                WHERE object_id = @object_id AND is_primary_key = 1",
            "            ) THEN 1 ELSE 0",
            "        END;",
            "",
            "        IF @has_pk = 1",
            "            PRINT N'SKIP (has PK / use CT grants): ' + @schema + N'.' + @table;",
            "        ELSE IF NOT EXISTS (",
            "            SELECT 1 FROM cdc.change_tables WHERE source_object_id = @object_id",
            "        )",
            "            PRINT N'SKIP (CDC not enabled): ' + @schema + N'.' + @table;",
            "        ELSE",
            "        BEGIN",
            "            SET @sql = N'GRANT SELECT ON '",
            "                + QUOTENAME(@schema) + N'.' + QUOTENAME(@table)",
            "                + N' TO [' + " + principal_expr + " + N']';",
            "            EXEC sp_executesql @sql;",
            "",
            "            SELECT @capture_instance = ct.capture_instance",
            "            FROM cdc.change_tables ct",
            "            WHERE ct.source_object_id = @object_id;",
            "",
            "            SET @cdc_change_table = @capture_instance + N'_CT';",
            "            IF @capture_instance IS NOT NULL",
            "               AND OBJECT_ID(QUOTENAME(N'cdc') + N'.' + QUOTENAME(@cdc_change_table)) IS NOT NULL",
            "            BEGIN",
            "                SET @sql = N'GRANT SELECT ON ' + QUOTENAME(N'cdc') + N'.' + QUOTENAME(@cdc_change_table)",
            "                    + N' TO [' + " + principal_expr + " + N']';",
            "                EXEC sp_executesql @sql;",
            "                PRINT N'CDC grants applied: ' + @schema + N'.' + @table",
            "                    + N' + cdc.' + @cdc_change_table;",
            "            END",
            "            ELSE IF @capture_instance IS NOT NULL",
            "                PRINT N'WARN CDC change table missing: cdc.' + @capture_instance + N'_CT';",
            "        END",
            "    END",
            "",
            "    FETCH NEXT FROM grant_cursor INTO @table;",
            "END",
            "",
            "CLOSE grant_cursor;",
            "DEALLOCATE grant_cursor;",
            "GO",
            "",
        ]
    )
    return lines


def generate_ct_grants_sql(
    client: ClientEntry,
    tables: list[EffectiveTable],
    principal_placeholder: str = "<KEEP_USER_ID>",
) -> str:
    """Grant SELECT + VIEW CHANGE TRACKING on PK tables with CT enabled."""
    placeholder = _sql_ident(principal_placeholder)
    values = _table_list_values_sql(tables)
    lines = [
        f"-- Auto-generated by ipac_delta_sync for client: {client.client_nm}",
        f"-- Source DB: {client.src_db_nm}, schema: {client.src_db_schema}",
        "-- Replace principal below before executing.",
        "-- Applies to tables WITH PK and CT enabled (skips non-PK tables).",
        "",
        f"USE [{_sql_ident(client.src_db_nm)}];",
        "GO",
        "",
        f"DECLARE @principal SYSNAME = N'{placeholder}';",
        "",
    ]
    lines.extend(
        _generate_dynamic_ct_grants_body(_sql_literal(client.src_db_schema), values)
    )
    return "\n".join(lines).rstrip() + "\n"


def generate_cdc_grants_sql(
    client: ClientEntry,
    tables: list[EffectiveTable],
    principal_placeholder: str = "<KEEP_USER_ID>",
) -> str:
    """Grant SELECT on non-PK CDC source tables and cdc capture instances."""
    placeholder = _sql_ident(principal_placeholder)
    values = _table_list_values_sql(tables)
    lines = [
        f"-- Auto-generated by ipac_delta_sync for client: {client.client_nm}",
        f"-- Source DB: {client.src_db_nm}, schema: {client.src_db_schema}",
        "-- Replace principal below before executing.",
        "-- Applies to tables WITHOUT PK with CDC enabled (skips PK tables).",
        "",
        f"USE [{_sql_ident(client.src_db_nm)}];",
        "GO",
        "",
        f"DECLARE @principal SYSNAME = N'{placeholder}';",
        "",
    ]
    lines.extend(
        _generate_dynamic_cdc_grants_body(_sql_literal(client.src_db_schema), values)
    )
    return "\n".join(lines).rstrip() + "\n"


def generate_table_pk_ct_status_sql(
    client: ClientEntry,
    tables: list[EffectiveTable],
) -> str:
    """Report PK + CT status for resolved active tables (common + overrides)."""
    values = _table_list_values_sql(tables)
    schema_literal = _sql_literal(client.src_db_schema)
    lines = _client_sql_header(
        client,
        "active tables PK + CT status check (common catalog + client overrides)",
    )
    lines.extend(
        [
            "SET NOCOUNT ON;",
            "",
            "DECLARE @schema SYSNAME = N'" + schema_literal + "';",
            "",
            "-- Database-level Change Tracking",
            "SELECT",
            "    DB_NAME() AS database_name,",
            "    CASE WHEN EXISTS (SELECT 1 FROM sys.change_tracking_databases WHERE database_id = DB_ID())",
            "        THEN 1 ELSE 0 END AS db_ct_enabled;",
            "",
        ]
    )
    lines.extend(_table_list_setup(schema_literal, values))
    lines.extend(
        [
            "-- Per-table: exists, primary key, change tracking",
            "SELECT",
            "    tl.table_name,",
            "    CASE WHEN t.object_id IS NOT NULL THEN 1 ELSE 0 END AS table_exists,",
            "    CASE WHEN pk.object_id IS NOT NULL THEN 1 ELSE 0 END AS has_pk,",
            "    CASE WHEN ct.object_id IS NOT NULL THEN 1 ELSE 0 END AS ct_enabled,",
            "    CASE",
            "        WHEN t.object_id IS NULL THEN 'MISSING_TABLE'",
            "        WHEN pk.object_id IS NULL THEN 'NO_PK'",
            "        WHEN ct.object_id IS NULL THEN 'CT_NOT_ENABLED'",
            "        ELSE 'CT_OK'",
            "    END AS pk_ct_status",
            "FROM #table_list tl",
            "LEFT JOIN sys.tables t",
            "    ON t.object_id = OBJECT_ID(QUOTENAME(@schema) + '.' + QUOTENAME(tl.table_name))",
            "LEFT JOIN (",
            "    SELECT object_id FROM sys.indexes WHERE is_primary_key = 1",
            ") pk ON pk.object_id = t.object_id",
            "LEFT JOIN sys.change_tracking_tables ct ON ct.object_id = t.object_id",
            "ORDER BY tl.table_name;",
            "",
            "-- Summary",
            "SELECT pk_ct_status, COUNT(*) AS table_count",
            "FROM (",
            "    SELECT",
            "        CASE",
            "            WHEN t.object_id IS NULL THEN 'MISSING_TABLE'",
            "            WHEN pk.object_id IS NULL THEN 'NO_PK'",
            "            WHEN ct.object_id IS NULL THEN 'CT_NOT_ENABLED'",
            "            ELSE 'CT_OK'",
            "        END AS pk_ct_status",
            "    FROM #table_list tl",
            "    LEFT JOIN sys.tables t",
            "        ON t.object_id = OBJECT_ID(QUOTENAME(@schema) + '.' + QUOTENAME(tl.table_name))",
            "    LEFT JOIN (",
            "        SELECT object_id FROM sys.indexes WHERE is_primary_key = 1",
            "    ) pk ON pk.object_id = t.object_id",
            "    LEFT JOIN sys.change_tracking_tables ct ON ct.object_id = t.object_id",
            ") s",
            "GROUP BY pk_ct_status",
            "ORDER BY pk_ct_status;",
            "",
            "-- Problems only",
            "SELECT table_name, pk_ct_status",
            "FROM (",
            "    SELECT",
            "        tl.table_name,",
            "        CASE",
            "            WHEN t.object_id IS NULL THEN 'MISSING_TABLE'",
            "            WHEN pk.object_id IS NULL THEN 'NO_PK'",
            "            WHEN ct.object_id IS NULL THEN 'CT_NOT_ENABLED'",
            "            ELSE 'CT_OK'",
            "        END AS pk_ct_status",
            "    FROM #table_list tl",
            "    LEFT JOIN sys.tables t",
            "        ON t.object_id = OBJECT_ID(QUOTENAME(@schema) + '.' + QUOTENAME(tl.table_name))",
            "    LEFT JOIN (",
            "        SELECT object_id FROM sys.indexes WHERE is_primary_key = 1",
            "    ) pk ON pk.object_id = t.object_id",
            "    LEFT JOIN sys.change_tracking_tables ct ON ct.object_id = t.object_id",
            ") r",
            "WHERE r.pk_ct_status <> 'CT_OK'",
            "ORDER BY r.table_name;",
            "GO",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def write_enable_ct_or_cdc_sql(
    client: ClientEntry,
    tables: list[EffectiveTable],
    sql_dir: Path | str,
) -> str:
    out_dir = Path(sql_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{client.client_nm}_enable_ct_or_cdc.sql"
    out_file.write_text(generate_enable_ct_or_cdc_sql(client, tables), encoding="utf-8")
    return str(out_file)


def write_ct_grants_sql(
    client: ClientEntry,
    tables: list[EffectiveTable],
    sql_dir: Path | str,
    principal_placeholder: str = "<KEEP_USER_ID>",
) -> str:
    out_dir = Path(sql_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{client.client_nm}_grant_ct_access.sql"
    out_file.write_text(
        generate_ct_grants_sql(client, tables, principal_placeholder=principal_placeholder),
        encoding="utf-8",
    )
    return str(out_file)


def write_cdc_grants_sql(
    client: ClientEntry,
    tables: list[EffectiveTable],
    sql_dir: Path | str,
    principal_placeholder: str = "<KEEP_USER_ID>",
) -> str:
    out_dir = Path(sql_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{client.client_nm}_grant_cdc_access.sql"
    out_file.write_text(
        generate_cdc_grants_sql(client, tables, principal_placeholder=principal_placeholder),
        encoding="utf-8",
    )
    return str(out_file)


def write_table_pk_ct_status_sql(
    client: ClientEntry,
    tables: list[EffectiveTable],
    sql_dir: Path | str,
) -> str:
    out_dir = Path(sql_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{client.client_nm}_active_tables_pk_ct_status.sql"
    out_file.write_text(generate_table_pk_ct_status_sql(client, tables), encoding="utf-8")
    return str(out_file)


def write_source_replication_sql(
    client: ClientEntry,
    tables: list[EffectiveTable],
    sql_dir: Path | str,
    principal_placeholder: str = "<KEEP_USER_ID>",
) -> tuple[str, str, str, str]:
    """Write enable + CT grants + CDC grants + PK/CT status check (4 scripts total)."""
    enable_path = write_enable_ct_or_cdc_sql(client, tables, sql_dir)
    ct_grant_path = write_ct_grants_sql(
        client, tables, sql_dir, principal_placeholder=principal_placeholder
    )
    cdc_grant_path = write_cdc_grants_sql(
        client, tables, sql_dir, principal_placeholder=principal_placeholder
    )
    status_path = write_table_pk_ct_status_sql(client, tables, sql_dir)
    return enable_path, ct_grant_path, cdc_grant_path, status_path
