"""Generate SQL artifacts for source SQL Server preparation."""

from __future__ import annotations

from pathlib import Path

from util.models import ClientEntry, EffectiveTable


def _sql_ident(name: str) -> str:
    return name.replace("]", "]]")


def generate_enable_ct_sql(
    client: ClientEntry,
    tables: list[EffectiveTable],
    ct_grantee: str = "",
) -> str:
    """Create idempotent SQL script to enable Change Tracking for effective tables."""
    lines = [
        f"-- Auto-generated by ipac_delta_sync for client: {client.client_nm}",
        f"-- Source DB: {client.src_db_nm}, schema: {client.src_db_schema}",
        "-- Purpose: enable SQL Server Change Tracking on source tables for Lakeflow CDC",
        "",
        f"USE [{client.src_db_nm}];",
        "GO",
        "",
    ]

    grantee = ct_grantee.strip()
    if grantee:
        lines.extend(
            [
                f"-- Grants will be applied to principal: [{_sql_ident(grantee)}]",
                "",
                f"GRANT VIEW DATABASE STATE TO [{_sql_ident(grantee)}];",
                "GO",
                "",
            ]
        )

    for table in sorted(tables, key=lambda t: t.table_nm.lower()):
        table_ident = _sql_ident(table.table_nm)
        schema_ident = _sql_ident(client.src_db_schema)
        lines.extend(
            [
                (
                    "IF NOT EXISTS ("
                    "SELECT 1 FROM sys.change_tracking_tables "
                    f"WHERE object_id = OBJECT_ID(N'[{schema_ident}].[{table_ident}]')"
                    ")"
                ),
                "BEGIN",
                (
                    f"    ALTER TABLE [{schema_ident}].[{table_ident}] "
                    "ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);"
                ),
                "END",
                "GO",
                "",
            ]
        )
        if grantee:
            lines.extend(
                [
                    (
                        f"GRANT SELECT, VIEW CHANGE TRACKING ON "
                        f"[{schema_ident}].[{table_ident}] TO [{_sql_ident(grantee)}];"
                    ),
                    "GO",
                    "",
                ]
            )

    return "\n".join(lines).rstrip() + "\n"


def write_enable_ct_sql(
    client: ClientEntry,
    tables: list[EffectiveTable],
    sql_dir: Path | str,
    ct_grantee: str = "",
) -> str:
    """Write <client_nm>_enable_ct.sql under src/<client_nm>/sql."""
    out_dir = Path(sql_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{client.client_nm}_enable_ct.sql"
    out_file.write_text(
        generate_enable_ct_sql(client, tables, ct_grantee=ct_grantee),
        encoding="utf-8",
    )
    return str(out_file)


def generate_ct_grants_sql(
    client: ClientEntry,
    tables: list[EffectiveTable],
    principal_placeholder: str = "<KEEP_USER_ID>",
) -> str:
    """Create SQL script that grants CT/SELECT access for all effective tables."""
    placeholder = _sql_ident(principal_placeholder)
    schema_ident = _sql_ident(client.src_db_schema)
    lines = [
        f"-- Auto-generated by ipac_delta_sync for client: {client.client_nm}",
        f"-- Source DB: {client.src_db_nm}, schema: {client.src_db_schema}",
        "-- Replace principal below before executing.",
        f"DECLARE @principal SYSNAME = N'{placeholder}';",
        "",
        f"USE [{_sql_ident(client.src_db_nm)}];",
        "GO",
        "",
        "DECLARE @sql NVARCHAR(MAX);",
        "",
        "-- DB-level permission needed by ingestion workflows",
        "SET @sql = N'GRANT VIEW DATABASE STATE TO [' + REPLACE(@principal, ']', ']]') + N']';",
        "EXEC sp_executesql @sql;",
        "GO",
        "",
    ]

    for table in sorted(tables, key=lambda t: t.table_nm.lower()):
        table_ident = _sql_ident(table.table_nm)
        lines.extend(
            [
                f"IF OBJECT_ID(N'[{schema_ident}].[{table_ident}]') IS NOT NULL",
                "BEGIN",
                (
                    "    SET @sql = N'GRANT SELECT, VIEW CHANGE TRACKING ON "
                    f"[{schema_ident}].[{table_ident}] TO [' + REPLACE(@principal, ']', ']]') + N']';"
                ),
                "    EXEC sp_executesql @sql;",
                "END",
                "GO",
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def write_ct_grants_sql(
    client: ClientEntry,
    tables: list[EffectiveTable],
    sql_dir: Path | str,
    principal_placeholder: str = "<KEEP_USER_ID>",
) -> str:
    """Write <client_nm>_grant_ct_access.sql under src/<client_nm>/sql."""
    out_dir = Path(sql_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / f"{client.client_nm}_grant_ct_access.sql"
    out_file.write_text(
        generate_ct_grants_sql(
            client,
            tables,
            principal_placeholder=principal_placeholder,
        ),
        encoding="utf-8",
    )
    return str(out_file)
